config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :animegifs
  get 'animegif/search' => 'pages#search'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'popular' => 'pages#ratingsort'
  get 'random' => 'pages#random'
  scope :api do
    #Note APIDota = Dota 2 api records
    #     APILOL = LOL 2 API Records (LOL has way too many images)
    scope :dota2 do
      get 'main' => 'pages#dota2main'
      get 'icons' => 'pages#dota2icon'
      get 'icons/all' => 'pages#dota2icon_all'
      get 'popular' => 'pages#dota2_popular'
    end
    scope :lol do
      get 'main' => 'pages#lolmain'
      get 'fanart' => 'pages#lolfanart'
      get 'random' => 'pages#lolrandom'
    end
  end

  scope :projects do
    get 'web' => 'projects#web'
    get 'mobile' => 'projects#mobile'
  end
  get 'projects' => 'projects#index'

end

app/models/animegif.rb
class Animegif < ActiveRecord::Base
	validates_uniqueness_of :name
	include PgSearch
  	pg_search_scope :search_by_name, :against => :name,:using => {
                    :tsearch => {:prefix => true}
                  }

	  extend FriendlyId
  		friendly_id :name, use: :slugged
end

app/models/api_dota.rb
class ApiDota < ActiveRecord::Base
  mount_uploader :img, DefaultUploader
end

app/models/api_lol.rb
class ApiLol < ActiveRecord::Base
  mount_uploader :img, DefaultUploader
end

app/models/cron_gif.rb
class CronGif
	def initialize
		tries ||= 3
    	url = "https://www.reddit.com/r/animegifs/.json?limit=100"
	    begin
	      subreddit_json = JSON.load open(url,'User-Agent' => 'wraithseeker')
	    rescue OpenURI::HTTPError => error
	        puts "#{error}, retrying..."
	        sleep(2.minutes)
	        retry unless (tries -= 1).zero?
	    end
    	subreddit_json["data"]["children"].map do |s| 
	       	validExtensions = ["jpeg","jpg","gif","gifv","png"]
	        title = s["data"]["title"]
	        url  = s["data"]["url"]
	        permalink = s["data"]["permalink"]
	        redditurl = "http://www.reddit.com" + permalink
	        upvotes = s["data"]["ups"]
	        downvotes = s["data"]["downs"]
	        score = s["data"]["score"]
	       	if url.include? "gfycat"
		        sleep(1)
	        	urlCajax = parseGfycatURI(url)
	         	begin
	            	gfycatData = JSON.load open(urlCajax)
	          	rescue OpenURI::HTTPError => error
	              puts "Can't open #{urlCajax}"
	              next
	          	end  
          		gfycatWebm = gfycatData["gfyItem"]["webmUrl"]
          		gfycatMp4  = gfycatData["gfyItem"]["mp4Url"]
	          	creation = Animegif.find_or_create_by(name: title,url: url,urlType: "gfycat",
	                         webmurl: gfycatWebm,mp4url: gfycatMp4)
	          	if creation != nil
	            	creation.update_attribute(:score,score)
		            creation.update_attribute(:redditurl,redditurl)
	          	else
	            	puts "ERROR!, please check your rake file"
	          	end 
	          	p url
       		elsif url.include? "imgur"
       			next if (!validExtensions.any? {|s| url.include?(s)} && url.include?("imgur") )
         		if url.include? "gifv" 
          			url.sub!("gifv","gif")
        		end
		        puts "#{url}"
		        urlwebm = url.dup
		        urlmp4 = url.dup
	          	urlposter = url.dup
	         	urlposter.slice!(".gif?1")
	         	urlposter.slice!(".gif")
     			urlposter << "l.jpg"
		        url.slice!("http:")
		        url.slice!("https:")
		        webm = urlwebm.sub!("gif","webm")
		        mp4 = urlmp4.sub!("gif","mp4")
		        creation = Animegif.find_or_create_by(name: title,url: url,urlType: urlposter,
		                     webmurl: webm,mp4url: mp4)
	          	if creation != nil
	            	creation.update_attribute(:score,score)
		            creation.update_attribute(:redditurl,redditurl)
	          	else
		            puts "ERROR!, please check your rake file"
	          	end
	    	end
		end
		puts "Success"	
	end

	def parseGfycatURI(url)
		if url.include? "gifv" 
        	url.sub!("gifv","gif")
      	end
		url.slice!("https://gfycat.com/")
	    url.slice!("http://gfycat.com/")
	    urlCajax = "https://gfycat.com/cajax/get/#{url}"
	    return urlCajax
   	end

end

app/controllers/animegifs_controller.rb
class AnimegifsController < ApplicationController

   
	def new
		@Animegif = Animegif.new
	end
	
	def index

	end
	def show
		@Animegif = Animegif.friendly.find(params[:id])

	end

	def create
		@Animegif = User.new
		if @Animegif.save
			redirect_to @user
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	
	def index
		#For some reason per_page is -2 the actual number
		@animegif = Animegif.paginate(:page => params[:page], :per_page => 12).order('created_at DESC')
		##Post.page(params[:page]).order('created_at DESC')	
	end

	def random
		@animegif = Animegif.limit(12).order("RANDOM()")
	end

	def search
		@animegif = Animegif.search_by_name(params[:search])
	end

	def ratingsort
		@animegif = Animegif.paginate(:page => params[:page], :per_page => 12).order('score DESC')
	end

	# API

	def dota2main
 		@item = ApiDota.where(:api_type => 'dota2_wallpaper').limit(250).order("RANDOM()")
 		render json: @item, root: false,each_serializer: ApiDotasSerializer
	end
 
 	def dota2icon
 		@item = ApiDota.where(:api_type => 'dota2_icon')
 		render json: @item, root: false,each_serializer: ApiDotasSerializer
 	end
 
	def dota2icon_all
 		@item = ApiDota.where(:api_type => 'dota2_category_images')
 		render json: @item, root: false,each_serializer: ApiDotasSerializer
 	end

 	def dota2_popular
 		@item = ApiDota.where(:api_type => 'dota2_popular').limit(250).order("RANDOM()")
 		render json: @item, root: false,each_serializer: ApiDotasSerializer
 	end
 
	def lolmain
		@item = ApiLol.where(:api_type => 'main').limit(250).order("RANDOM()")
		render json: @item, root: false,each_serializer: ApiLolsSerializer
	end

	def lolfanart
		@item = ApiLol.where(:api_type => 'fanart').limit(250).order("RANDOM()")
		render json: @item, root: false,each_serializer: ApiLolsSerializer
	end

	def lolrandom
		@item = ApiLol.limit(500).order("RANDOM()")
		render json: @item, root: false,each_serializer: ApiLolsSerializer
	end
	
	# END API #
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def web

	end

	def mobile

	end

	def index
		render layout: 'project'
	end
end

app/helpers/animegifs_helper.rb
module AnimegifsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/animegifs/index.html.erb
<h1>Hi</h1>

app/views/animegifs/show.html.erb
<% title @Animegif.name %>
<div class="container">
	<div class="row" style="margin-bottom:15px;">
		<div class="col-lg-12">
			<%= link_to root_path do %> 
 				<button type="button" class="btn btn-primary btn-md back-padding ">Back</button>
 			<% end %>
 			<h3 class="text-primary" style="display:inline;">
 				<%= @Animegif.name %>
				<% if !@Animegif.redditurl.nil? %>
					<%= link_to image_tag("redditicon.png",style:"margin-left:30px;"), @Animegif.redditurl.sub("http://","https://"),:rel => "nofollow" %>
				<% end %>
			</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-9 col-md-12 col-xs-12">	
		<% if @Animegif.urlType.include? "gfycat" %>
			<div class="video">

					<div class="embed-responsive embed-responsive-16by9">

					<video class="resize" autoplay poster="https://thumbs.gfycat.com/<%= @Animegif.url %>-poster.jpg" loop>
							<source src=<%= @Animegif.webmurl.sub("http://","https://") %> type="video/webm">
							<source src=<%= @Animegif.mp4url.sub("http://","https://") %> type="video/mp4">
						</video>  

					</div>
			</div>
		<% else %>
		<div class="video">
			<div class="embed-responsive embed-responsive-16by9">
				<video class="embed-responsive-item" autoplay poster=<%= @Animegif.urlType.sub("http://","https://")%> loop>	
			        <source src=<%= @Animegif.webmurl.sub("http://","https://") %> type="video/webm">
			         <source src=<%= @Animegif.mp4url.sub("http://","https://") %> type="video/mp4">	
			 	</video>  
			</div>
		</div>
		<% end %>
	</div>
		<!-- End of col-lg-9 column -->
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="Anikawaii is the place for the latest and hottest anime gifs online." name="description">
  <title>
  <%= if content_for?(:title) then yield(:title) + ' | ' end %>
  Anikawaii - Anime GIFs
</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  <script type"text/javascript" src="https://test.gfycat.com/gfycat_test_may18.js"></script> 
  <meta name="viewport" content="width=device-width">
</head>
<body>
	  <div class="container-fullwidth">
   
      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href=<%= root_path %>><span class="logotitle">Anikawaii</span></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
               <li>
                  <a href=<%= popular_path %>><h4 class="navitem">Popular</h4></a>
               </li>
                <li>
                <a href=<%= random_path %>><h4 class="navitem">Random</h4></a>
              </li>
              <li>
                <a href=<%= about_path %>><h4 class="navitem">About</h4></a>
              </li>
               <li>
                <a href="https://www.visualnoveler.com/vns"><h4 class="navitem">Visualnoveler</h4></a>
              </li>
              
            </ul>
           
          <div class="input-group" id="custom-search-input">
            <!-- typeahead !-->
             <%= form_tag(animegif_search_path, :method => "get", class: "navbar-form", id: "search-form" ) do %>
                <%= text_field_tag :search, params[:search], class: "form-control search-query", placeholder: "Search Anime Gifs" %>
                <div class="input-group-btn">
                  <%= button_tag(type: "submit", class: "btn") do %>
                    <span class=" glyphicon glyphicon-search"></span>
                  <% end %>
                </div>
             <% end %>
           </div>
 
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    </div> <!-- /container -->


<%= yield %>






</body>


</html>

app/views/layouts/project.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="Projects" name="description">
  <title>
  <%= if content_for?(:title) then yield(:title) + ' | ' end %>
  Projects
</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width">
</head>

<%= yield %>







</body>


</html>

app/views/pages/_gfycat.html.erb
<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 thumb">
	<div class="video">
		<div class="module">
			<%= render 'rating',gif: gif %>
			<div class="embed-responsive embed-responsive-16by9">
				<%= link_to(gif) do %>
					<video class="embed-responsive-item" poster="https://thumbs.gfycat.com/<%= gif.url %>-poster.jpg" loop>   
			            <source src=<%= gif.webmurl.sub("http://","https://") %> type="video/webm">
			            <source src=<%= gif.mp4url.sub("http://","https://") %> type="video/mp4">	
        
 					</video>  

 				<% end %>
 			</div>
 		</div>
 	</div>
</div>

app/views/pages/_imgur.html.erb
<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 thumb">
	<div class="video">
		<div class="module">
			<%= render 'rating',gif: gif %>

			<div class="embed-responsive embed-responsive-16by9">
				<%= link_to(gif) do %>
					<video class="embed-responsive-item" poster="<%= gif.urlType.sub("http://","https://") %>" loop>   
							  
			        	<source src=<%= gif.webmurl.sub("http://","https://") %> type="video/webm">
			        	<source src=<%= gif.mp4url.sub("http://","https://") %> type="video/mp4">	
		            
			 		</video>  

			 	<% end %>
			 </div>
		</div>
	</div>
</div>

app/views/pages/_rating.html.erb
<header>
<!-- title of gif <h3><%= gif.name %></h3> -->

<div class="gif-column">
	<i class="fa fa-star fa-lg" style="color:yellow;" aria-hidden="true"></i>
	<h5 style="display:inline;margin-top:10px;position:relative;top:2px;padding:5px;"><%= gif.score %></h4>
</div>
</header>

app/views/pages/about.html.erb
<div class="container">
<div class="row">

	<div class="col-lg-4">
	<%= image_tag("gochuumon.jpg",class: "img-responsive ", :alt => "gochuumon what") %>
</div>
	<div class="col-lg-12">
		<h2>What is AniKawaii?</h2>
		
	</div>
	<div class="col-lg-12 indent-text">
		<p><span class="read">AniKawaii is built using Rails along with bootstrap as the front-end. <br>It is a hobby project that wraithseeker made to learn Rails and have fun. It presents anime gifs in a clean and sleek format.</span></p>
	</div>

	<div class="col-lg-12">
		<h2>Where does AniKawaii get the anime GIFs from?</h2>
	</div>

	<div class="col-lg-12 indent-text">
		<p><span class="read">The gifs are fetched and parsed from anime subreddits.</span></p>
	</div>

	<div class="col-lg-12">
		<h2>Current Project</h2>
	</div>
	<div class="col-lg-12 indent-text">
		<p><span class="read">I'm currently developing stuff at <a href="http://www.visualnoveler.com">Visualnoveler</a>, a website for people to track and discover visual novels.</span></p>
	</div>
	

	<div class="col-lg-12">
		<h2>Future Features?</h2>
	</div>
	<div class="col-lg-12 indent-text">
		<ul class="list-group">
		  <li><span class="read">More sources of Animegifs</span></li>
		  <li><span class="read">Short anime video clips</span></li>
		</ul>
	</div>

	
</div>
</div>

<footer>        
      <a href="https://github.com/wraithseeker/AniKawaii">

        <h5 class="text-center text-info" style="color:black;">
        	<i class="fa fa-github-alt fa-lg" style="padding-right:5px;position:relative;bottom:2px;" aria-hidden="true"></i>
        	Anikawaii Github
        </h5>
      </a>
  </footer>

app/views/pages/dota2main.html.erb
<h1>doto</h1>

app/views/pages/index.html.erb
<div class="container">

	<div class="row">
		<div class="col-lg-12">
		</div>

		<% @animegif.each do |gif| %>
			<% title = gif.url %>
			<% urlClass = gif.urlType %>

			<% if urlClass.include? "gfycat" %>
				<%= render 'gfycat',gif: gif %>
		 	<% else %> 
		 	<!-- imgur !-->
		 		<%= render 'imgur',gif: gif %>
				<!-- ALTERNATIVE, for now only HTML5 videos -->
			<% end %>
		<% end %>
	</div>
		<div class="flickr_pagination">
			<%= will_paginate @animegif, renderer: BootstrapPagination::Rails %>
		</div>
</div>

  <footer>        
      <a href="https://github.com/wraithseeker/AniKawaii">

        <h5 class="text-center text-info" style="color:black;">
        	<i class="fa fa-github-alt fa-lg" style="padding-right:5px;position:relative;bottom:2px;" aria-hidden="true"></i>
        	Anikawaii Github
        </h5>
      </a>
  </footer>

app/views/pages/random.html.erb
<div class="container">

	<div class="row">
		<div class="col-lg-12">
		</div>

		<% @animegif.each do |gif| %>
			<% title = gif.url %>
			<% urlClass = gif.urlType %>
			<% if urlClass.include? "gfycat" %>
				<%= render 'gfycat',gif: gif %>
		 	<% else %> 
		 	<!-- imgur !-->
		 		<%= render 'imgur',gif: gif %>
				<!-- ALTERNATIVE, for now only HTML5 videos -->
			<% end %>
		<% end %>
	</div>
	
</div>

app/views/pages/ratingsort.html.erb
<div class="container">

	<div class="row">
		<div class="col-lg-12">
		</div>

		<% @animegif.each do |gif| %>
			<% title = gif.url %>
			<% urlClass = gif.urlType %>
			<% if urlClass.include? "gfycat" %>
				<%= render 'gfycat',gif: gif %>
		 	<% else %> 
		 	<!-- imgur !-->
		 		<%= render 'imgur',gif: gif %>
				<!-- ALTERNATIVE, for now only HTML5 videos -->
			<% end %>
		<% end %>
	</div>
		<div class="flickr_pagination">
			<%= will_paginate @animegif, renderer: BootstrapPagination::Rails %>
		</div>
</div>

app/views/pages/search.html.erb
<div class="container">

	<div class="row">
		<div class="col-lg-12">
		</div>

		<% @animegif.each do |gif| %>
			<% title = gif.url %>
			<% urlClass = gif.urlType %>
			<% if urlClass.include? "gfycat" %>
				<%= render 'gfycat',gif: gif %>
		 	<% else %> 
		 	<!-- imgur !-->
		 		<%= render 'imgur',gif: gif %>
				<!-- ALTERNATIVE, for now only HTML5 videos -->
			<% end %>
		<% end %>
	</div>
		
</div>

app/views/projects/index.html.erb
<div class="container">
	<div class="row">
		<h2 class="text-center"> Wraithseeker - Full Stack Web and iOS Developer</h2>
		<div class="col-md-6">
			<h3 class="text-center">Webdev Projects</h3>
			<div class="row">
				<div class="col-md-12">
					<h4 class="text-center"><a href="https://visualnoveler.com">Visualnoveler</a> - <a href="https://github.com/wraithseeker/Visualnoveler">Github link</a></h4>
					<h4 class="text-center">October 2015 - Ongoing</h4>
					<p>Visualnoveler's backend uses the Ruby on Rails framework and the front-end uses Bootstrap. Amazon S3 is used for file storage. The blogging engine was customly built which uses markdown as a renderer and supports image uploads. OAuth login using Facebook and Google+ is supported</p>
					<p>Languages used: Ruby,Javascript,CSS,Coffeescript</p>
					<p>Hosted on DigitalOcean</p>

					<h4 class="text-center"> <a href="http://forums.visualnoveler.com">Visualnoveler forums</a></h4>
					<h4 class="text-center">October 2015 - Ongoing</h4>
					<p>Visualnoveler forums is a self-hosted implementation of <a href="http://www.discourse.org/">Discourse</a> which uses SSO to sign users in from Visualnoveler.</p>
					<p>Hosted on DigitalOcean</p>

					<h4 class="text-center"> <a href="http://anikawaii.com">Anikawaii</a> - <a href="https://github.com/wraithseeker/Anikawaii">Github link</a></h4>
					<h4 class="text-center">August 2015 - Ongoing</h4>
					<p>Anikawaii is built using Rails and uses Bootstrap as the front-end which uses the reddit JSON responses to update the gif gallery daily in the website. Anikawaii also hosts the mobile API endpoints needed for my mobile applications to function. 

					<p>Hosted on DigitalOcean</p>
					<p>Languages used: Ruby,Javascript,CSS</p>

					<h4 class="text-center"> <a href="http://wraithseeker.com">Wraithseeker</a></h4>
					<h4 class="text-center">February 2016 - February 2016</h4>
					<p>My personal blogging website which uses Wordpress that migrated from Bluehost to Digitalocean. 

					<p>Hosted on DigitalOcean</p>
					<p>Languages used: Ruby,Javascript,CSS</p>
				</div>
			</div>
		</div>

		<div class="col-md-6">
			<h3 class="text-center">iOS Mobile Projects</h3>
			<div class="row">
				<div class="col-md-12">
					<h4 class="text-center"> <a href="https://itunes.apple.com/us/app/make-the-path/id990331714?ls=1&mt=8">Make the Path</a></h4>
					<h4 class="text-center">May 2015 - July 2015</h4>
					<p>Make the Path is a 2D iOS game created using SpriteKit with Xcode.</p>
					<p>Languages used: Swift,Objective-C</p>

					<h4 class="text-center"> <a href="https://itunes.apple.com/us/app/awwnime-anime-fanart/id1046419607?ls=1&mt=8">Awwnime</a></h4>
					<h4 class="text-center">October 2015 - November 2015</h4>
					<p> iOS gallery app which communicates with an API and is built with a custom gallery template which is used for the other image apps below.</p>
					<p>Languages used: Swift,Objective-C</p>

					<h4 class="text-center"> <a href="https://itunes.apple.com/us/app/anime-coverage-daily-anime/id998928477?ls=1&mt=8">Anime Coverage</a></h4>
					<h4 class="text-center">May 2015 - June 2015</h4>
					<p>iOS RSS reader app.</p>
					<p>Languages used: Swift,Objective-C</p>

					<h4 class="text-center"> <a href="https://itunes.apple.com/us/app/detective-cat-find-missing/id1046472560?ls=1&mt=8">Detective Cat</a></h4>
					<h4 class="text-center">September 2015 - November 2015</h4>
					<p>Cross platform game for Android and iOS built using Unity.</p>
					<p>Languages used: C#</p>

					<h4 class="text-center"> <a href="https://itunes.apple.com/us/app/hd-wallpapers-heroes-for-dota/id1045660127?ls=1&mt=8">HD Wallpapers & Heroes for Dota 2</a></h4>
					<h4 class="text-center">October 2015 - October 2015</h4>
					<p>iOS gallery app which communicates with the API hosted on my website.</p>
					<p>Languages used: Swift,Objective-C</p>

					<h4 class="text-center"> <a href="https://itunes.apple.com/us/app/leagueart-wallpapers-league/id982748530?ls=1&mt=8">LeagueArt Wallpapers</a></h4>
					<h4 class="text-center">October 2015 - October 2015</h4>
					<p>iOS gallery app which communicates with the API hosted on my website.</p>
					<p>Languages used: Swift,Objective-C</p>
				</div>
			</div>
		</div>
	</div>
</div>